### ISSUE TITLE
Splash path on OS X incorrect

### ISSUE THREAD

**Issue by jasonferrier** [NathanW2/qgis_hats#17]
[`value = splash + "\\"`](https://github.com/NathanW2/qgis_hats/blob/master/src/qgis_hats/__init__.py#L181)
Should be `//` for OS X.

**Comment by jasonferrier** [comment]
Tested this on my system and it works on OS X 10.11.6 // QGIS 3.4.2. Untested on Windows.
`value = splash + os.sep`

**Comment by raymondnijssen** [comment]
Getting an error on the same line, but I think it is different. Guess my splash==None
(qgis 3.5.0-master on linux)
---

Couldn't load plugin 'qgis_hats' due to an error when calling its initGui() method 

TypeError: unsupported operand type(s) for +: 'NoneType' and 'str' 
Traceback (most recent call last):
  File "/home/raymond/programs/qgis-master/share/qgis/python/qgis/utils.py", line 344, in startPlugin
    plugins[packageName].initGui()
  File "/home/raymond/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_hats/__init__.py", line 164, in initGui
    self.show_the_hats()
  File "/home/raymond/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_hats/__init__.py", line 178, in show_the_hats
    value = splash + "\\"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by NathanW2** [comment]
Fixed in latest
