### ISSUE TITLE
ImportError: No module named error 

### ISSUE THREAD

**Issue by SergioGollino** [NathanW2/qgis_hats#4]
On QGIS 2.14.9 ltr, the plugin won't start and gives this error:
```

Couldn't load plugin 'qgis_hats'

ImportError: No module named error

Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 281, in loadPlugin
    __import__(packageName)
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/sergio.gollino/.qgis2/python/plugins\qgis_hats\__init__.py", line 14, in 
    from urllib.error import HTTPError
  File "C:/OSGEO4~1/apps/qgis-ltr/./python\qgis\utils.py", line 572, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named error
```

Thank you!

**Comment by SteveLowman** [comment]
I confirm this is an issue. Colleagues are distressed!
